name: school_attendance
description: "Appwrite StarterKit in Flutter"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7

  get_it: ^8.0.3

  auto_route: ^8.1.0

  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0

  appwrite: 17.0.0

  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0

  intl: ^0.20.2
  logger: ^2.5.0
  connectivity_plus: ^6.0.0
  flutter_animate: ^4.5.2

  pdf: ^3.11.3
  path_provider: ^2.1.3

  csv: ^6.0.0

  form_validator: ^2.1.1

  url_launcher: ^6.3.1
  window_manager: ^0.4.3
  flutter_dotenv: ^5.1.0

dependency_overrides:
  flutter_web_auth_2: 4.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  hive_generator: ^2.0.1
  bloc_test: ^10.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

assets:
  - assets/images/
  - assets/icons/